<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Using RMSTdesign to Find Optimal Trial Designs • RMSTdesign</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Using RMSTdesign to Find Optimal Trial Designs">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">RMSTdesign</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Compare-to-SSRMST.html">Compare Power from RMSTdesign and SSRMST Packages</a>
    </li>
    <li>
      <a href="../articles/GOG111-Trial.html">Trial design example based on GOG111 trial data</a>
    </li>
    <li>
      <a href="../articles/Optimal-trial-design.html">Using RMSTdesign to Find Optimal Trial Designs</a>
    </li>
    <li>
      <a href="../articles/RMSTdesign-package-validation.html">RMSTdesign-package-validation</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/anneae/RMSTdesign">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Using RMSTdesign to Find Optimal Trial Designs</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/anneae/RMSTdesign/blob/master/vignettes/Optimal-trial-design.Rmd"><code>vignettes/Optimal-trial-design.Rmd</code></a></small>
      <div class="hidden name"><code>Optimal-trial-design.Rmd</code></div>

    </div>

    
    
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(RMSTdesign)</code></pre></div>
<p>We use a simple example to discuss different criteria for selecting an optimal trial and how to do it. In some cases the optimal trial design may be the one that has the smallest sample size, regardless of duration; in other cases it may be the one with the shortest duration, regardless of sample size, and in other cases, you may be looking for a balance between the two.</p>
<p>We consider planning a trial where we expect survival time distributions in both the control and treatment groups follow exponential distributions, which implies proportional hazards. We expect the median survival time in the control group to be 3 years and the new treatment to reduce mortality risk by 33% (hazard ratio = 0.67). In the disease we are studying, 3 years is a clinically important landmark, so we choose <span class="math inline">\(\tau\)</span>= 3 years. We plan to do a one-sided test, and we want to estimate the sample size to achieve 80% power with a one-sided Type I error of 0.025.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">con&lt;-<span class="kw"><a href="../reference/survdef.html">survdef</a></span>(<span class="dt">times =</span> <span class="dv">3</span>, <span class="dt">surv =</span> <span class="fl">0.5</span>) 
trt&lt;-<span class="kw"><a href="../reference/survdef.html">survdef</a></span>(<span class="dt">haz =</span> <span class="fl">0.67</span><span class="op">*</span>con<span class="op">$</span><span class="kw">h</span>(<span class="dv">1</span>))
<span class="kw"><a href="../reference/plotsurvdef.html">plotsurvdef</a></span>(con, trt, <span class="dv">5</span>)</code></pre></div>
<p><img src="Optimal-trial-design_files/figure-html/unnamed-chunk-2-1.png" width="700"></p>
<p>We can consult Table 2 to get a rough estimate of the number of patients we will need for a hazard ratio of 0.67 with <span class="math inline">\(\tau\)</span> equal to median survival in the control group. We will need 552 patients (276 in each arm) to achieve 80% power. This estimate doesn’t take into account administrative censoring. This code obtains the same result.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/RMSTpow.html">RMSTpow</a></span>(con, trt, <span class="dt">k1 =</span> <span class="dv">0</span>, <span class="dt">k2 =</span> <span class="dv">3</span>, <span class="dt">tau =</span> <span class="dv">3</span>, <span class="dt">power =</span> <span class="fl">0.8</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 552</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMST</span>
<span class="co">#&gt; [1] 0.8008182</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.8008182</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.8708721</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.8708721</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pKME</span>
<span class="co">#&gt; [1] 1</span></code></pre></div>
<p>The trial with all patients followed to time <span class="math inline">\(\tau\)</span> is optimal in terms of minimal sample size. Also, you are sure to be able to estimate RMST difference at time <span class="math inline">\(\tau\)</span> because no patients will be censored before time <span class="math inline">\(\tau\)</span>. Note that extending followup time beyong <span class="math inline">\(\tau\)</span> provides no benefit in terms of either power or pKME (the probability RMST difference will be estimable with the Kaplan-Meier estimator), though it does increase the power of the standard log-rank test calculated with all avaiable follow-up (the quantity <code>powerLRToverC</code> in the output below).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/RMSTpow.html">RMSTpow</a></span>(con, trt, <span class="dt">k1 =</span> <span class="dv">0</span>, <span class="dt">k2 =</span> <span class="dv">10</span>, <span class="dt">tau =</span> <span class="dv">3</span>, <span class="dt">power =</span> <span class="fl">0.8</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 552</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMST</span>
<span class="co">#&gt; [1] 0.8008182</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.8008182</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.9908296</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.8709119</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pKME</span>
<span class="co">#&gt; [1] 1</span></code></pre></div>
<p>We may also be interested in the trial design with the shortest duration. Our function <code>shortest_duration</code> can find that design, but you need to input an accrual rate. Let’s assume the accrual rate is 552/4 = 138 patients per year. Notice that under this assumption, accruing 552 patients takes 4 years, and a trial where you accrue 552 patients and follow all patients for 3 years takes 7 years to complete.</p>
<p>This code finds the shortest duration trial that has the specified power and pKME (default is 0.95):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/shortest_duration.html">shortest_duration</a></span>(con, trt, <span class="dv">3</span>, .<span class="dv">8</span>, <span class="dv">552</span><span class="op">/</span><span class="dv">4</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 668</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $k1</span>
<span class="co">#&gt; [1] 4.84058</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $k2</span>
<span class="co">#&gt; [1] 0</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $duration</span>
<span class="co">#&gt; [1] 4.84058</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.8006054</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.8586702</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.8219996</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pMKE</span>
<span class="co">#&gt; [1] 1</span></code></pre></div>
<p>The shortest duration trial enrolls 668 patients and takes 4.84 years to complete.</p>
<p>Our shortest duration function also optimizes over sample size, within trial designs that have the shortest duration. For example, if we thought we could accrue 1000 patients per year, either a trial that recruits for the whole duration and lasts 3.013386 years, or a trial that recruits for 0.554 years, then follows patients for 2.459386 years for a total trial duration of 0.554 + 2.459386 = 3.013386 years will meet the required threshold for power and pKME, as shown below. However, the second trial needs about 1/6 as many patients (554 versus 3012). Our <code>shortest_duration</code> function will return the latter trial design, the smallest sample size trial out of the trials with the shortest duration.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/RMSTpow.html">RMSTpow</a></span>(con, trt, <span class="fl">3.013386</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="fl">3.013386</span><span class="op">*</span><span class="dv">1000</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 3012</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMST</span>
<span class="co">#&gt; [1] 0.9996733</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.9996733</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.9996469</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.9996469</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pKME</span>
<span class="co">#&gt; [1] 0.9500287</span>
<span class="kw"><a href="../reference/RMSTpow.html">RMSTpow</a></span>(con, trt, <span class="fl">0.554</span>, <span class="fl">2.459386</span>, <span class="dv">3</span>, <span class="fl">0.554</span><span class="op">*</span><span class="dv">1000</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 554</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMST</span>
<span class="co">#&gt; [1] 0.8011577</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.8011577</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.848365</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.8483505</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pKME</span>
<span class="co">#&gt; [1] 0.9517473</span>
<span class="kw"><a href="../reference/shortest_duration.html">shortest_duration</a></span>(con, trt, <span class="dv">3</span>, .<span class="dv">8</span>, <span class="dv">1000</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 554</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $k1</span>
<span class="co">#&gt; [1] 0.554</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $k2</span>
<span class="co">#&gt; [1] 2.459386</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $duration</span>
<span class="co">#&gt; [1] 3.013386</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.8011577</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.848365</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.8483505</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pMKE</span>
<span class="co">#&gt; [1] 0.9517498</span></code></pre></div>
<p>Sometimes a trial that is only a little longer than the shortest duration trial can offer a large reduction in sample size. One way to explore this is using our <code>shortest_duration</code> function with the option <code>altdesign = T</code>. You add a multiplier which defines the trial length you are willing to consider, relative to the shortest duration trial, on a multiplicative scale. For example, if you set <code>multiplier</code> = 1.1, the function will find the smallest sample size trial with duration equal to 1.1 times the shorest possible duration. In other words, you are willing to consider a trial that is 10% longer than the optimal trial. In the example above, the shortest possible trial was 4.84 years, so a multiplier of 1.1 indicates considering trials of length 5.3.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/shortest_duration.html">shortest_duration</a></span>(con, trt, <span class="dv">3</span>, .<span class="dv">8</span>, <span class="dv">552</span><span class="op">/</span><span class="dv">4</span>, <span class="dt">altdesign =</span> T, <span class="dt">multiplier =</span> <span class="fl">1.1</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 568</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $k1</span>
<span class="co">#&gt; [1] 4.115942</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $k2</span>
<span class="co">#&gt; [1] 1.202079</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $duration</span>
<span class="co">#&gt; [1] 5.318021</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.800984</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.8894142</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.8410203</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pMKE</span>
<span class="co">#&gt; [1] 1</span></code></pre></div>
<p>We see that by extending the trial by about half a year, we can reduce the number of required patients by 100.</p>
<p>We now have several candidate trial designs. We can explore each design further by plotting power as a function of each design parameter using the <code>plot = T</code> option. We focus on the trial that enrolls 552 patients over 4 years, then follows them for 3 years. In the following plots, the red lines represent the power of the log-rank test using all available followup, the blue lines represent the log-rank test using data to time <code>tau</code>, and the black lines represent the power of the test for difference in RMST restricted to time <code>tau</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/RMSTpow.html">RMSTpow</a></span>(con, trt, <span class="dt">k1 =</span> <span class="dv">4</span>, <span class="dt">k2 =</span> <span class="dv">3</span>, <span class="dt">tau =</span> <span class="dv">3</span>, <span class="dt">n =</span> <span class="dv">552</span>, <span class="dt">plot =</span> T)</code></pre></div>
<p><img src="Optimal-trial-design_files/figure-html/unnamed-chunk-8-1.png" width="700"></p>
<pre><code>#&gt; $n
#&gt; [1] 552
#&gt; 
#&gt; $powerRMST
#&gt; [1] 0.8008182
#&gt; 
#&gt; $powerRMSTToverC
#&gt; [1] 0.8008182
#&gt; 
#&gt; $powerRMSTCoverT
#&gt; [1] NA
#&gt; 
#&gt; $powerLRToverC
#&gt; [1] 0.9539556
#&gt; 
#&gt; $powerLRCoverT
#&gt; [1] NA
#&gt; 
#&gt; $powerLRtauToverC
#&gt; [1] 0.8709213
#&gt; 
#&gt; $powerLRtauCoverT
#&gt; [1] NA
#&gt; 
#&gt; $pKME
#&gt; [1] 1</code></pre>
<p>The plots show us that we can reduce accrual time and maintain power, but that would mean we need to enroll the same number of patients in a shorter time, which may not be practical. We also see that we could reduce follow-up time by about a year without a significant loss in power.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/RMSTpow.html">RMSTpow</a></span>(con, trt, <span class="dt">k1 =</span> <span class="dv">4</span>, <span class="dt">k2 =</span> <span class="dv">2</span>, <span class="dt">tau =</span> <span class="dv">3</span>, <span class="dt">n =</span> <span class="dv">552</span>)
<span class="co">#&gt; $n</span>
<span class="co">#&gt; [1] 552</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMST</span>
<span class="co">#&gt; [1] 0.7998204</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTToverC</span>
<span class="co">#&gt; [1] 0.7998204</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerRMSTCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRToverC</span>
<span class="co">#&gt; [1] 0.9229113</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauToverC</span>
<span class="co">#&gt; [1] 0.8597414</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $powerLRtauCoverT</span>
<span class="co">#&gt; [1] NA</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $pKME</span>
<span class="co">#&gt; [1] 1</span></code></pre></div>
<p>We see that reducing <span class="math inline">\(k_2\)</span> to 2 went slightly too far, as power has dropped below 0.8. Using trial and error we find that <span class="math inline">\(k_2\)</span>=2.1 is adequate to preserves power and pKME, reducing total trial duration to 6.1 years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/RMSTpow.html">RMSTpow</a></span>(con, trt, <span class="dt">k1 =</span> <span class="dv">4</span>, <span class="dt">k2 =</span> <span class="fl">2.1</span>, <span class="dt">tau =</span> <span class="dv">3</span>, <span class="dt">n =</span> <span class="dv">552</span>, <span class="dt">plot =</span> T)</code></pre></div>
<p><img src="Optimal-trial-design_files/figure-html/unnamed-chunk-10-1.png" width="700"></p>
<pre><code>#&gt; $n
#&gt; [1] 552
#&gt; 
#&gt; $powerRMST
#&gt; [1] 0.8001678
#&gt; 
#&gt; $powerRMSTToverC
#&gt; [1] 0.8001678
#&gt; 
#&gt; $powerRMSTCoverT
#&gt; [1] NA
#&gt; 
#&gt; $powerLRToverC
#&gt; [1] 0.9270544
#&gt; 
#&gt; $powerLRCoverT
#&gt; [1] NA
#&gt; 
#&gt; $powerLRtauToverC
#&gt; [1] 0.8619928
#&gt; 
#&gt; $powerLRtauCoverT
#&gt; [1] NA
#&gt; 
#&gt; $pKME
#&gt; [1] 1</code></pre>
<p>The plots show us that, under the new design, reducing follow-up time will reduce power. Increasing sample size or shortening accrual while keeping sample size constant would increase power, but may not be desirable or possible. Similar plots could be used to explore and tweak the other candidate designs.</p>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Anne Eaton.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
